export const POTLanguages = [
  {"name": "Abkhaz", "code": "ab"},
  {"name": "Afar", "code": "aa"},
  {"name": "Africanos", "code": "af"},
  {"name": "Akan", "code": "ak"},
  {"name": "Albania", "code": "sq"},
  {"name": "Amárico", "code": "am"},
  {"name": "Árabe", "code": "ar"},
  {"name": "Aragonés", "code": "an"},
  {"name": "Armenio", "code": "hy"},
  {"name": "Assamese", "code": "as"},
  {"name": "Avaric", "code": "av"},
  {"name": "Avestan", "code": "ae"},
  {"name": "Aymara", "code": "ay"},
  {"name": "Azerbaiyán", "code": "az"},
  {"name": "Bambara", "code": "bm"},
  {"name": "Bashkir", "code": "ba"},
  {"name": "Vasco", "code": "eu"},
  {"name": "Belarús", "code": "be"},
  {"name": "Bengalí", "code": "bn"},
  {"name": "Bihari", "code": "bh"},
  {"name": "Bislama", "code": "bi"},
  {"name": "Bosnia", "code": "bs"},
  {"name": "Breton", "code": "br"},
  {"name": "Búlgaro", "code": "bg"},
  {"name": "Burmese", "code": "my"},
  {"name": "Catalán", "code": "ca"},
  {"name": "Chamorro", "code": "ch"},
  {"name": "Chechenio", "code": "ce"},
  {"name": "Chichewa, Chewa, Nyanja", "code": "ny"},
  {"name": "Chino", "code": "zh"},
  {"name": "Chuvashia", "code": "cv"},
  {"name": "Cornualles", "code": "kw"},
  {"name": "Corso", "code": "co"},
  {"name": "Cree", "code": "cr"},
  {"name": "Croacia", "code": "hr"},
  {"name": "Checo", "code": "cs"},
  {"name": "Danés", "code": "da"},
  {"name": "Divehi, Dhivehi, Maldivas", "code": "dv"},
  {"name": "Holandés", "code": "nl"},
  {"name": "Dzongkha", "code": "dz"},
  {"name": "Inglés", "code": "en"},
  {"name": "Esperanto", "code": "eo"},
  {"name": "Estonia", "code": "et"},
  {"name": "Ewe", "code": "ee"},
  {"name": "Faroese", "code": "fo"},
  {"name": "Fiji", "code": "fj"},
  {"name": "Finlandés", "code": "fi"},
  {"name": "Francés", "code": "fr"},
  {"name": "Fula, Fulah, Pulaar, Pular", "code": "ff"},
  {"name": "Galicia", "code": "gl"},
  {"name": "Georgiano", "code": "ka"},
  {"name": "Alemán", "code": "de"},
  {"name": "Griego Moderno", "code": "el"},
  {"name": "Guaraní", "code": "gn"},
  {"name": "Gujarati", "code": "gu"},
  {"name": "Haitiano, creole haitiano", "code": "ht"},
  {"name": "Hausa", "code": "ha"},
  {"name": "Hebreo (moderno)", "code": "he"},
  {"name": "Herero", "code": "hz"},
  {"name": "Hindi", "code": "hi"},
  {"name": "Hiri Motu", "code": "ho"},
  {"name": "Húngaro", "code": "hu"},
  {"name": "Interlingua", "code": "ia"},
  {"name": "Indonesio", "code": "id"},
  {"name": "Interlingue", "code": "ie"},
  {"name": "Irlanda", "code": "ga"},
  {"name": "Igbo", "code": "ig"},
  {"name": "Inupiaq", "code": "ik"},
  {"name": "Ido", "code": "io"},
  {"name": "Islandés", "code": "is"},
  {"name": "Italiano", "code": "it"},
  {"name": "Inuktitut", "code": "iu"},
  {"name": "Japonés", "code": "ja"},
  {"name": "Javanés", "code": "jv"},
  {"name": "Kalaallisut, Groenlandia", "code": "kl"},
  {"name": "Canarés", "code": "kn"},
  {"name": "Kanuri", "code": "kr"},
  {"name": "Cachemira", "code": "ks"},
  {"name": "Kazajstán", "code": "kk"},
  {"name": "Khmer", "code": "km"},
  {"name": "Kikuyu, Gikuyu", "code": "ki"},
  {"name": "Kinyarwanda", "code": "rw"},
  {"name": "Kirguises, Kirguistán", "code": "ky"},
  {"name": "Komi", "code": "kv"},
  {"name": "Kongo", "code": "kg"},
  {"name": "Corea", "code": "ko"},
  {"name": "Kurdo", "code": "ku"},
  {"name": "Kwanyama, Kuanyama", "code": "kj"},
  {"name": "Latin", "code": "la"},
  {"name": "Luxemburgués, Luxemburgués", "code": "lb"},
  {"name": "Luganda", "code": "lg"},
  {"name": "Limburgués, Limburgan, Limburger", "code": "li"},
  {"name": "Lingala", "code": "ln"},
  {"name": "Lao", "code": "lo"},
  {"name": "Lituano", "code": "lt"},
  {"name": "Luba-Katanga", "code": "lu"},
  {"name": "Letonia", "code": "lv"},
  {"name": "Manx", "code": "gv"},
  {"name": "Macedonia", "code": "mk"},
  {"name": "Madagascar", "code": "mg"},
  {"name": "Malayo", "code": "ms"},
  {"name": "Malayalam", "code": "ml"},
  {"name": "Maltés", "code": "mt"},
  {"name": "Māori", "code": "mi"},
  {"name": "Maratí (Marathi)", "code": "mr"},
  {"name": "De las Islas Marshall", "code": "mh"},
  {"name": "Mongolia", "code": "mn"},
  {"name": "Nauru", "code": "na"},
  {"name": "Navajo, Navaho", "code": "nv"},
  {"name": "Noruego Bokmål", "code": "nb"},
  {"name": "Ndebele del Norte", "code": "nd"},
  {"name": "Nepali", "code": "ne"},
  {"name": "Ndonga", "code": "ng"},
  {"name": "Noruego Nynorsk", "code": "nn"},
  {"name": "Noruego", "code": "no"},
  {"name": "Nuosu", "code": "ii"},
  {"name": "Ndebele del sur", "code": "nr"},
  {"name": "Occitano", "code": "oc"},
  {"name": "Ojibwe, Ojibwa", "code": "oj"},
  {"name": "Antiguo eslavo eclesiástico, Iglesia eslava, eslavo eclesiástico, antiguo Búlgaro, Esclavo viejo", "code": "cu"},
  {"name": "Oromo", "code": "om"},
  {"name": "Oriya", "code": "or"},
  {"name": "Osetia del Sur, osetio", "code": "os"},
  {"name": "Panjabi, Punjabi", "code": "pa"},
  {"name": "Pāli", "code": "pi"},
  {"name": "Persa", "code": "fa"},
  {"name": "Polaco", "code": "pl"},
  {"name": "Pashto, Pushto", "code": "ps"},
  {"name": "Portugués", "code": "pt"},
  {"name": "Quechua", "code": "qu"},
  {"name": "Romanche", "code": "rm"},
  {"name": "Kirundi", "code": "rn"},
  {"name": "Rumania, Moldavia, Moldavan", "code": "ro"},
  {"name": "Ruso", "code": "ru"},
  {"name": "Sánscrito (samskrta)", "code": "sa"},
  {"name": "Sardo", "code": "sc"},
  {"name": "Sindhi", "code": "sd"},
  {"name": "Sami del norte", "code": "se"},
  {"name": "Samoa", "code": "sm"},
  {"name": "Sango", "code": "sg"},
  {"name": "Serbio", "code": "sr"},
  {"name": "Gaélico escocés, gaélico", "code": "gd"},
  {"name": "Shona", "code": "sn"},
  {"name": "Cingalés, singalés", "code": "si"},
  {"name": "Eslovaca", "code": "sk"},
  {"name": "Esloveno", "code": "sl"},
  {"name": "Somalí", "code": "so"},
  {"name": "Southern Sotho", "code": "st"},
  {"name": "Español", "code": "es"},
  {"name": "Sundanese", "code": "su"},
  {"name": "Swahili", "code": "sw"},
  {"name": "Swati", "code": "ss"},
  {"name": "Sueco", "code": "sv"},
  {"name": "Tamil", "code": "ta"},
  {"name": "Telugu", "code": "te"},
  {"name": "Tayikistán", "code": "tg"},
  {"name": "Tailandia", "code": "th"},
  {"name": "Tigrinya", "code": "ti"},
  {"name": "Tibetano estándar, Tibetano, Central", "code": "bo"},
  {"name": "Turkmenistán", "code": "tk"},
  {"name": "Tagalo", "code": "tl"},
  {"name": "Tswana", "code": "tn"},
  {"name": "Tonga (Islas Tonga)", "code": "to"},
  {"name": "Turco", "code": "tr"},
  {"name": "Tsonga", "code": "ts"},
  {"name": "Tártara", "code": "tt"},
  {"name": "Twi", "code": "tw"},
  {"name": "Tahitian", "code": "ty"},
  {"name": "Uighur, Uyghur", "code": "ug"},
  {"name": "Ucrania", "code": "uk"},
  {"name": "Urdu", "code": "ur"},
  {"name": "Uzbeko", "code": "uz"},
  {"name": "Venda", "code": "ve"},
  {"name": "Vietnamita", "code": "vi"},
  {"name": "Volapük", "code": "vo"},
  {"name": "Valonia", "code": "wa"},
  {"name": "Galés", "code": "cy"},
  {"name": "Wolof", "code": "wo"},
  {"name": "Oeste de Frisia", "code": "fy"},
  {"name": "Xhosa", "code": "xh"},
  {"name": "Yiddish", "code": "yi"},
  {"name": "Yoruba", "code": "yo"},
  {"name": "Zhuang, Chuang", "code": "za"},
  {"name": "Zulu", "code": "zu"}
];
